var newspapers =
[
	{
		'name'  : 'Sabah',
		'site'  : 'http://www.sabah.com.tr/',
		'rss'   : 'http://www.sabah.com.tr/rss/Gundem.xml',
		'owner' : 'Turkuvaz Medya / Çalık Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/sabah_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://egazete.sabah.com.tr/eGazete/image/www_sabah_com_tr/@Y/@n/@j/1',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/001_p.jpg',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/sabah_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/sabah.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/sabah_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/sabah-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/sabah.jpg'
	},
	{
		'name'  : 'Takvim',
		'site'  : 'http://www.takvim.com.tr',
		'rss'   : 'http://www.takvim.com.tr/rss/AnaSayfa.xml',
		'owner' : 'Turkuvaz Medya / Çalık Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/takvim_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://egazete.takvim.com.tr/eGazete/image/www_takvim_com_tr/@Y/@j/@n/1',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/takvim_@Y-@m-@d.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/002_p.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/takvim.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/takvim_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/takvim-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/takvim.jpg'
	},
	{
		'name'  : 'Fotomaç',
		'site'  : 'http://www.fotomac.com.tr/',
		'rss'   : 'http://www.fotomac.com.tr/rss/Anasayfa.xml',
		'owner' : 'Turkuvaz Medya / Çalık Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/fotomac_@Y-@m-@d.jpg',
		'ctgry' : 'Spor',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/fotomac_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/fotomac.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/003_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/fotomac_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/fotomac-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/fotomac.jpg'
	},
	{
		'name'  : 'Akşam',
		'site'  : 'http://www.aksam.com.tr/',
		'rss'   : 'http://www.aksam.com.tr/cache/rss.xml',
		'owner' : 'Türkmedya Grubu / Sancak Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/aksam_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/aksam_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/aksam.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/004_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/aksam_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/aksam-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/aksam.jpg'
	},
	{
		'name'  : 'Yeni Şafak',
		'site'  : 'http://www.yenisafak.com.tr/',
		'rss'   : 'http://www.yenisafak.com.tr/rss/',
		'owner' : 'Albayrak Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yeni-safak_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yeni-safak_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yenisafak.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/005_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/yenisafak_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/yenisafak-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yeni_safak.jpg'
	},
	{
		'name'  : 'Star',
		'site'  : 'http://www.star.com.tr',
		'rss'   : 'http://www.stargazete.com/rss/mansetler.xml',
		'owner' : 'Star Medya Grubu',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/star_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/star_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/star.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/006_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/star_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/star-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/star.jpg'
	}/**/,
	{
		'name'  : 'Hürriyet',
		'site'  : 'http://www.hurriyet.com.tr',
		'rss'   : 'http://rss.hurriyet.com.tr/rss.aspx?sectionId=2',
		'owner' : 'Doğan Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/hurriyet_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/hurriyet_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/hurriyet.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/007_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/hurriyet_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/hurriyet-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/hurriyet.jpg'
	},
	{
		'name'  : 'Habertürk',
		'site'  : 'http://www.haberturk.com/',
		'rss'   : 'http://www.haberturk.com/rss',
		'owner' : 'Ciner Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/haberturk_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/haberturk_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/haberturk.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/008_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/haberturk_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/haberturk-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/haberturk.jpg'
	},
	{
		'name'  : 'Zaman',
		'site'  : 'http://www.zaman.com.tr',
		'owner' : 'Feza Gazetecilik / Samanyolu',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/zaman_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/zaman_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/zaman.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/009_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/zaman_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/zaman-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/zaman.jpg'
	},
	{
		'name'  : 'Vatan',
		'site'  : 'http://www.gazetevatan.com/',
		'rss'   : 'http://www.gazetevatan.com/rss/gundem.xml',
		'owner' : 'Demirören Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/vatan_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/vatan_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/vatan.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/010_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/vatan_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/vatan-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/vatan.jpg'
	},
	{
		'name'  : 'Türkiye',
		'site'  : 'http://www.turkiyegazetesi.com.tr',
		'rss'   : 'http://www.turkiyegazetesi.com.tr/rss/rss.xml',
		'owner' : 'İhlas Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/turkiye_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/turkiye_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/turkiye.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/011_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/turkiye_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/turkiye-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/turkiye.jpg'
	},
	{
		'name'  : 'Taraf',
		'site'  : 'http://www.taraf.com.tr',
		'rss'   : 'http://www.taraf.com.tr/sondakika.rss',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/taraf_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/taraf_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/taraf.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/012_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/taraf_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/taraf-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/taraf.jpg'
	},
	{
		'name'  : 'Posta',
		'site'  : 'http://www.posta.com.tr/',
		'rss'   : 'http://www.posta.com.tr/xml/rss/rss_1_0.xml',
		'owner' : 'Doğan Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/posta_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/posta_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/posta.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/014_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/posta_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/posta-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/posta.jpg'
	},
	{
		'name'  : 'Ortadoğu',
		'site'  : 'http://www.ortadogugazetesi.net/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/ortadogu_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/ortadogu_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/ortadogu.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/015_p.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/ortadogu-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/ortadogu.jpg'
	},
	{
		'name'  : 'Milliyet',
		'site'  : 'http://www.milliyet.com.tr/',
		'rss'   : 'http://www.milliyet.com.tr/D/rss/rss/RssSD.xml',
		'owner' : 'Demirören Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/milliyet_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/milliyet_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/milliyet.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/016_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/milliyet_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/milliyet-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/milliyet.jpg'
	},
	{
		'name'  : 'Milligazete',
		'site'  : 'http://www.milligazete.com.tr/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/milli-gazete_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/milli-gazete_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/milligazete.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/017_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/milligazete_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/milligazete-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/milli_gazete.jpg'
	},
	{
		'name'  : 'Güneş',
		'site'  : 'http://www.gunes.com',
		'owner' : 'Türkmedya Grubu / Sancak Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/gunes_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://www.gunes.com/images/@Y/@m/@d/gne1_1280.jpg',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/gunes_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/gunes.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/018_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/gunes_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/gunes-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/gunes.jpg'
	},
	{
		'name'  : 'Cumhuriyet',
		'site'  : 'http://www.cumhuriyet.com.tr',
		'rss'   : 'http://www.cumhuriyet.com.tr/rss/son_dakika.xml',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/cumhuriyet_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/cumhuriyet_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/cumhuriyet.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/019_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/cumhuriyet_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/cumhuriyet-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/cumhuriyet.jpg'
	},
	{
		'name'  : 'Fanatik',
		'site'  : 'http://www.fanatik.com.tr/',
		'owner' : 'Doğan Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/fanatik_@Y-@m-@d.jpg',
		'ctgry' : 'Spor',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/fanatik_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/fanatik.jpg',
		'trkvz' : 'http://i.tmgrup.com.tr/aktuel/galeri/gununmansetleri/gunun-mansetleri-@d@m@Y/020_p.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/fanatik_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/fanatik-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/fanatik.jpg'
	},
	{
		'name'  : 'Yeni Asya',
		'site'  : 'http://www.yeniasya.com.tr',
		'rss'   : 'http://www.yeniasya.com.tr/rss_haber.asp',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yeniasya_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yeniasya_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yeniasya.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/yeniasya_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/yeniasya-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yeni_asya.jpg'
	},
	{
		'name'  : 'Dünya',
		'site'  : 'http://www.dunya.com/',
		'rss'   : 'http://www.dunya.com/rss/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/dunya_@Y-@m-@d.jpg',
		'ctgry' : 'Ekonomi',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/dunya_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/dunya.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/dunya_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/dunya-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/dunya.jpg'
	},
	{
		'name'  : 'Bugün',
		'site'  : 'http://www.bugun.com.tr/',
		'rss'   : 'http://www.bugun.com.tr/haberler.xml',
		'owner' : 'Koza İpek Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/bugun_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/bugun_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/bugun.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/bugun_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/bugun-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/bugun.jpg'
	},
	{
		'name'  : 'İstanbul Ticaret',
		'site'  : 'http://www.istanbulticaret.org.tr/',
		'owner' : 'İstanbul Ticaret Odası',
		'kucuk' : 'http://resim.ihlassondakika.com/Gazete/istanbulticaret/istanbul_ticaret_kucuk.jpeg',
		'ctgry' : 'Ekonomi',
		'ozgun' : '',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/istanbulticaret/istanbul_ticaret.jpeg'
	},
	{
		'name'  : 'Yeni Akit',
		'site'  : 'http://www.yeniakit.com.tr/',
		'rss'   : 'http://www.yeniakit.com.tr/haber/rss',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yeni-akit_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yeni-akit_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yeniakit.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/vakit_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/vakit-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yeni_akit.jpg'
	},
	{
		'name'  : 'Sözcü',
		'site'  : 'http://sozcu.com.tr/',
		'owner' : 'Estetik Yayıncılık',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/sozcu_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/sozcu_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/sozcu.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/sozcu_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/sozcu-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/sozcu.jpg'
	},
	{
		'name'  : 'Birgün',
		'site'  : 'http://www.birgun.net/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/birgun_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/birgun_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/birgun.jpg',
		'ihlas' : 'http://resim.ihlassondakika.com/Gazete/@d.@m.@Y/birgun_@d@m@y.jpeg',
		'hbrlr' : 'http://img.haberler.com/gazete/birgun-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/birgun.jpg'
	},
	{
		'name'  : 'Anayurt',
		'site'  : 'http://www.anayurtgazetesi.com',
		'kucuk' : 'http://img.haberler.com/gazete/anayurt-gazetesi/bugun_o.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://sayfa.anayurtgazetesi.com.tr/images2/@Y-@n-@j/1.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/anayurt.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/anayurt-gazetesi/bugun.jpg'
	},
	{
		'name'  : 'Aydınlık',
		'site'  : 'http://www.aydinlikgazete.com/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/aydinlik_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/aydinlik_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/aydinlik.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/aydinlik-gazetesi/bugun.jpg'
	},
	{
		'name'  : 'Evrensel',
		'site'  : 'http://www.evrensel.net/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/gunluk-evrensel_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/gunluk-evrensel_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/evrensel.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/evrensel-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/gunluk_evrensel.jpg'
	},
	{
		'name'  : 'Yeni Mesaj',
		'site'  : 'http://www.yenimesaj.com.tr/',
		'rss'   : 'http://www.yenimesaj.com.tr/?rss',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yeni-mesaj_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yeni-mesaj_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yenimesaj.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/yenisafak-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yeni_mesaj.jpg'
	},
	{
		'name'  : 'Yeni Çağ',
		'site'  : 'http://www.yenicaggazetesi.com.tr/',
		'rss'   : 'http://www.yenicaggazetesi.com.tr/rss/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yenicag_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yenicag_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yenicag.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/yeni-cag-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yeni_cag.jpg'
	},
	{
		'name'  : 'Todays Zaman',
		'site'  : 'http://www.todayszaman.com',
		'owner' : 'Feza Gazetecilik / Samanyolu',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/todays-zaman_@Y-@m-@d.jpg',
		'ctgry' : 'İngilizce',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/todays-zaman_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/todayszaman.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/todays-zaman-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/today_zaman.jpg'
	},
	{
		'name'  : 'Milat',
		'site'  : 'http://www.milatgazetesi.com/',
		'rss'   : 'http://www.milatgazetesi.com/rss.asp',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/milat_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://www.milatgazetesi.com/gazete/@d@m@Y.jpg',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/milat_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/milat.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/milat-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/milat.jpg'
	},
	{
		'name'  : 'Önce Vatan',
		'site'  : 'http://www.oncevatan.com.tr/',
		'rss'   : 'http://www.oncevatan.com.tr/rss.php',
		'kucuk' : 'http://img.haberler.com/gazete/once-vatan-gazetesi/bugun_o.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		'hbrlr' : 'http://img.haberler.com/gazete/once-vatan-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/once_vatan.jpg'
	},
	{
		'name'  : 'Yurt',
		'site'  : 'http://www.yurtgazetesi.com.tr/',
		'rss'   : 'http://www.yurtgazetesi.com.tr/rss.php',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/yurt_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://www.yurtgazetesi.com.tr/images/sayfalar/manAet.gif',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/yurt_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/yurt.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/yurt-gazetesi/bugun.jpg',
		'itrps' : 'http://www.memurlar.net/images/newspapers/@Y/@n/@j/yurt.jpg'
	},
	{
		'name'  : 'Özgür Gündem',
		'site'  : 'http://www.ozgur-gundem.com/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/ozgur-gundem_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/ozgur-gundem_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/ozgurgundem.jpg',
		'hbrlr' : 'http://img.haberler.com/gazete/ozgur-gundem-gazetesi/bugun.jpg'
	},
	{
		'name'  : 'Amk',
		'site'  : 'http://amkspor.com/',
		'rss'   : 'http://amkspor.com/feed/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/amk-gazetesi_@Y-@m-@d.jpg',
		'ctgry' : 'Spor',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/amk-gazetesi_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/amk.jpg'
	},
	{
		'name'  : 'Hürriyet Daily News',
		'site'  : 'http://www.hurriyetdailynews.com/',
		'rss'   : 'http://www.hurriyetdailynews.com/rss.aspx',
		'owner' : 'Doğan Holding',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/hurriyet-daily-news_@Y-@m-@d.jpg',
		'ctgry' : 'İngilizce',
		'ozgun' : '',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/hurriyet-daily-news_@Y-@m-@d.jpg',
		'bik'   : 'http://www.bik.gov.tr/gazeteler/dosya/hurriyetdailynews.jpg?dt='
	},
	{
		'name'  : 'Agos',
		'site'  : 'http://www.agos.com.tr/',
		'kucuk' : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/grid/agos_@Y-@m-@d.jpg',
		'ctgry' : 'Haber',
		'ozgun' : 'http://www.agos.com.tr/upload/images/AGOS%20SAYFA%201%2815%29.jpg',
		't24'   : 'https://s3.amazonaws.com/us.media.t24.com.tr/media/papers/full/agos_@Y-@m-@d.jpg'
	}//*/
];
